Repository project-group8/newJeans, pull requests merged in 2023-04, with the labels that each got.

#23 [fix] 상세페이지 수정
  config/s3.json
  controllers/cardposts.controller.js
  modules/multer.js
  package-lock.json
  package.json
  repositories/cardposts.repository.js
  routes/cardposts.route.js
Labels: documentation

#25 Feat/gunsun
  controllers/cardposts.controller.js
  modules/multer.js
  routes/cardposts.route.js
Labels: documentation

#26 [feat] pollTitle 추가
  models/cardpost.js
  package-lock.json
Labels: documentation

#27 [feat] chat test
  controllers/users.controller.js
  index.html
  package-lock.json
  package.json
  redis.js
  server.js
  services/users.service.js
Labels: enhancement

#29 [fix] 핫 게시글 3 -> 5개로 증가
  repositories/cardposts.repository.js
Labels: documentation

#30 [fix] Boom 보류함 포스트 등록 수정
  controllers/cardposts.controller.js
Labels: documentation

#31 [fix] res.locals.user에서 받는 값을 email -> userIdx로 수정함
  controllers/cardposts.controller.js
  repositories/users.repository.js
  services/cardposts.service.js
Labels: documentation

#36 [fix] level 주석 처리
  repositories/cardposts.repository.js
Labels: documentation

#43 [feat] 유저가 좋아요 했는지 구분가능한 상세 페이지
  controllers/cardposts.controller.js
  middlewares/allusersMiddleware.js
  repositories/cardposts.repository.js
  routes/cardposts.route.js
  services/cardposts.service.js
Labels: documentation

#45 [feat] postLike 수정 및 prefer 전반적인 개선
  controllers/cardposts.controller.js
  controllers/postlike.controller.js
  controllers/prefer.controller.js
  controllers/users.controller.js
  models/commentlike.js
  models/postlike.js
  models/prefer.js
  repositories/cardposts.repository.js
  repositories/postlike.repository.js
  repositories/prefer.repository.js
  routes/cardposts.route.js
  routes/index.js
  routes/postlike.route.js
  routes/prefer.route.js
  services/cardposts.service.js
  services/postlike.service.js
  services/prefer.service.js
Labels: documentation

#46 [fix] allusersMiddleware 토큰 재발급 삭제
  middlewares/allusersMiddleware.js
Labels: documentation

#47 [feat] likesCount 추가 좋아요 오류 수정
  repositories/cardposts.repository.js
Labels: documentation

#52 [fix] pollType 모델 추가 및 Null허용
  controllers/cardposts.controller.js
  models/cardpost.js
  repositories/cardposts.repository.js
Labels: documentation

#61 Feat/gunsun
  app.js
  controllers/cardposts.controller.js
  repositories/prefer.repository.js
  routes/cardposts.route.js
  services/cardposts.service.js
  services/prefer.service.js
Labels: documentation

#63 [fix] 투표기능 테스트
  services/cardposts.service.js
Labels: bug

#65 [fix] pollvalue 수정
  services/cardposts.service.js
Labels: bug

#67 [feat] chat 기능 추가
  controllers/chat.controller.js
  migrations/20230424115405-create-chat.js
  models/chat.js
  models/users.js
  repositories/chat.repository.js
  routes/chat.route.js
  routes/index.js
  services/chat.service.js
Labels: documentation

#68 [fix] 채팅기능 수정
  controllers/chat.controller.js
  repositories/chat.repository.js
  routes/chat.route.js
  services/chat.service.js
Labels: documentation

#69 [feat] sockt 추가 app.js에 추가함
  app.js
Labels: documentation

#74 [feat] entity 관계설정 수정
  package-lock.json
  package.json
  src/app.module.ts
  src/cardposts/cardposts.controller.ts
  src/cardposts/cardposts.module.ts
  src/cardposts/cardposts.service.ts
  src/cardposts/dto/cardposts.dto.ts
  src/cardposts/pipes/cardposts-category-trans.pipe.ts
  src/entities/CardPosts.entity.ts
  src/entities/Comments.entity.ts
  src/entities/PostLikes.entity.ts
  src/entities/Users.entity.ts
  src/migrations/1682475534741-migrations.ts
Labels: documentation

#82 [feat] 채팅
  controllers/cardposts.controller.js
  controllers/chat.controller.js
  models/chat.js
  models/chatsaves.js
  models/users.js
  package-lock.json
  package.json
  repositories/chat.repository.js
  routes/cardposts.route.js
  routes/chat.route.js
  routes/postlike.route.js
  services/chat.service.js
Labels: documentation

#84 Nestgunsun
  package-lock.json
  package.json
  src/app.module.ts
  src/cardposts/cardposts.controller.ts
  src/cardposts/cardposts.module.ts
  src/cardposts/cardposts.service.ts
  src/cardposts/pipes/cardposts-category-trans.pipe.ts
  src/chat/chat.controller.ts
  src/chat/chat.module.ts
  src/chat/chat.service.ts
  src/chat/dto/chat.dto.ts
  src/chat/pipes/chat.pipe.ts
  src/entities/ChatSaves.entity.ts
  src/middleware/allusersjwtauthguard.ts
  src/middleware/postCountUpMiddleware.ts
  src/middleware/uploads.middleware.ts
  src/migrations/1682663474121-migrations.ts
  src/post-like/post-like.controller.ts
  src/post-like/post-like.service.ts
  src/prefer/pipes/prefer.pipe.ts
  src/prefer/prefer.controller.ts
  src/prefer/prefer.service.ts
  src/uploads/uploads.controller.ts
  src/uploads/uploads.module.ts
  src/uploads/uploads.service.ts
Labels: documentation
